name: noScribe_nomkl
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - tk
  - pillow
  - pyyaml
  - appdirs
  - typing
  - pathlib
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - pyinstaller
  - nomkl
  - pip
  - pip:
    - customtkinter
    - elevate
    # - cpufeature # conflicts with (arm64) macOS
    - python-i18n
    - git+https://github.com/kaixxx/python-docx
    - git+https://github.com/kaixxx/pyannote-audio
    - auto-py-to-exe
