name: noScribe_nomkl
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - nomkl
  - tk # redundant, since already dependency of python
  - pillow
  - pyyaml
  - appdirs
  - typing
  - pathlib # should be removed from environment file
  - pyinstaller
  - pip
  - pip:
    - torch # need to be installed via pip for using nomkl
    - torchvision # need to be installed via pip for using nomkl
    - torchaudio # need to be installed via pip for using nomkl
    - customtkinter
    - elevate
    # - cpufeature # conflicts with (arm64) macOS
    - python-i18n
    - git+https://github.com/kaixxx/python-docx
    - git+https://github.com/kaixxx/pyannote-audio
    - auto-py-to-exe
